name: lint-code 

on:
  push:
    branches:
      - main
    paths:
      - "ansible/**"
  pull_request:
    branches:
      - main
    paths:
      - "ansible/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: "ansible/"
