---

- name: Update apk repositories
  when: ansible_distribution == 'Alpine'
  ansible.builtin.copy:
    content: |
      http://dl-cdn.alpinelinux.org/alpine/v3.19/main
      http://dl-cdn.alpinelinux.org/alpine/v3.19/community
      http://dl-cdn.alpinelinux.org/alpine/edge/main
      http://dl-cdn.alpinelinux.org/alpine/edge/community
      http://dl-cdn.alpinelinux.org/alpine/edge/testing
    dest: "/etc/apk/repositories"
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Install packages
  when: ansible_distribution == 'Alpine'
  ansible.builtin.package:
    name:
      - uuidgen
      - nfs-utils
      - ncurses-terminfo
      - open-iscsi
      - util-linux-bash-completion
      - lsblk
      - wipefs
      - sudo
      - cfdisk
      - tree
      - htop
      - vim
      - bash
      - rsync
      - unzip
      - gzip
      - tar
